esphome:
  name: heatpumpwifi
  friendly_name: "HeatPumpWiFi"

esp32:
  # board: esp32dev
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    # version: 5.5.4

external_components:
  - source:
      type: local
      path: ../components
    components: [heatpumpwifi]

heatpumpwifi:
  uart_id: heatpumpwifi_uart

uart:
  id: heatpumpwifi_uart
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 115200
  debug:
    direction: BOTH
    dummy_receiver: false
    debug_prefix: "[MODBUS] "
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes, debug_prefix);

logger:
  level: VERBOSE

button:
  - platform: restart
    name: "Restart"

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

output:
  - platform: gpio
    pin:
      number: GPIO14
      inverted: true
    id: output_user_led

light:
  - platform: binary
    id: user_led
    output: output_user_led
    name: "User LED"
    initial_state:
      state: false
    restore_mode: ALWAYS_OFF
